#ifndef __ERR_H_
#define __ERR_H_

typedef enum {
	STATUS_OK 			= 0,
	STATUS_GENERAL_ERROR 		= 1,
	STATUS_FILE_NOT_FOUND	 	= 2,
	STATUS_SHORT_READ 		= 3,
	STATUS_SHORT_WRITE 		= 4,
	STATUS_NO_MEMORY 		= 5,
	STATUS_FILE_CORRUPT 		= 6,
	STATUS_NOT_SUPPORTED	 	= 7,
	STATUS_NOT_IMPLEMENTED 		= 8,
	STATUS_BAD_FILE_DESCRIPTOR	= 9,
	STATUS_MEMORY_CORRUPTION	= 10,
	STATUS_INTERRUPTED 		= 11,
	STATUS_IO_ERROR 		= 12 ,
} STATUS;

#endif /* __ERR_H_ */
